device: cuda
camera:
  name: head
  aligned_depth_to_color: true
  depth_scale: 0.0010000000474974513
  color_intrinsics:
    width: 424
    height: 240
    fx: 303.0887145996094
    fy: 303.31781005859375
    cx: 212.41064453125
    cy: 128.03280639648438
  depth_intrinsics:
    width: 424
    height: 240
    fx: 303.0887145996094
    fy: 303.31781005859375
    cx: 212.41064453125
    cy: 128.03280639648438
pointcloud:
  use_rgb: true
  output_format: xyzrgb
crop:
  enabled: true
  frame: camera
  x:
  - -0.5
  - 0.5
  y:
  - -0.2
  - 0.5
  z:
  - 0.05
  - 1.2
sampling:
  enabled: true
  mode: "random"   # fps | stride | random | voxel | voxel_random | voxel_fps
  num_points: 1024
  voxel_size: 0.005
  seed: 42
  deterministic: false
  pad_mode: repeat
